"use client"

import { useState } from "react"
import { ArrowDownRight, ArrowUpRight, Check, Copy, Gamepad2, Mail, MousePointer2, Sparkles } from "lucide-react"

const projects = [
  { name:"Kishcare ERP", type:"Healthcare operations", year:"2024", color:"bg-acid", text:"A calmer command center for a busy healthcare ecosystem.", tags:["product design","frontend","systems"] },
  { name:"Enterprise HRMS", type:"People infrastructure", year:"2023", color:"bg-coral", text:"Making complex workforce workflows feel surprisingly human.", tags:["UX strategy","web app","scale"] },
  { name:"SportsConnectPro", type:"Community platform", year:"2022", color:"bg-paper", text:"A high-energy social platform for the sport-obsessed.", tags:["brand","interaction","launch"] },
]

export default function Home() {
  const [intro, setIntro] = useState(true); const [copied, setCopied] = useState(false); const [score, setScore] = useState(0); const [message, setMessage] = useState("")
  const share = async () => { await navigator.clipboard?.writeText(window.location.href); setCopied(true); setTimeout(()=>setCopied(false),1800) }
  const send = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form=new FormData(e.currentTarget); const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))}); setMessage(res.ok?'Signal received. I’ll get back to you soon.':'Something glitched. Please email me directly.'); if(res.ok)e.currentTarget.reset() }
  if (intro) return <main className="min-h-screen grid-bg noise flex items-center justify-center p-6"><div className="max-w-xl w-full"><div className="font-mono text-xs text-muted mb-10 flex justify-between"><span>SD / STUDIO_BOOT</span><span>v2.026</span></div><div className="border border-paper/20 p-6 md:p-10 bg-ink/80"><div className="flex items-center gap-3 text-acid font-mono text-xs mb-12"><span className="size-2 bg-acid rounded-full animate-pulse"/> systems online</div><h1 className="text-5xl md:text-8xl font-semibold tracking-[-.07em] leading-[.88]">Make it<br/><span className="text-acid">worth</span><br/>clicking.</h1><p className="font-mono text-sm text-muted mt-10 max-w-sm leading-6">An independent creative engineering studio for sharp ideas, useful weirdness, and products people remember.</p><button onClick={()=>setIntro(false)} className="mt-12 border border-acid text-acid px-5 py-3 font-mono text-xs hover:bg-acid hover:text-ink transition-colors">ENTER THE PLAYGROUND <ArrowUpRight className="inline ml-2 size-4"/></button></div></div></main>
  return <main className="noise overflow-hidden"><nav className="fixed top-0 z-20 w-full flex justify-between items-center px-5 md:px-10 py-5 mix-blend-difference"><a href="#top" className="font-mono text-sm">SD<span className="text-acid">_</span>STUDIO</a><div className="flex gap-4 items-center"><button onClick={share} aria-label="Copy page link" className="font-mono text-xs border border-paper/30 px-3 py-2 hover:border-acid hover:text-acid transition">{copied?<Check className="inline size-3 mr-1"/>:<Copy className="inline size-3 mr-1"/>}{copied?'COPIED':'SHARE'}</button><a href="#contact" className="font-mono text-xs text-acid">LET&apos;S TALK ↗</a></div></nav>
    <section id="top" className="min-h-screen grid-bg flex flex-col justify-end px-5 md:px-10 pb-12 pt-32"><div className="flex justify-between items-start mb-16"><span className="font-mono text-xs text-muted">01 / CREATIVE ENGINEER<br/>BASED IN NEPAL · WORKING EVERYWHERE</span><MousePointer2 className="text-acid float hidden md:block"/></div><div className="relative"><p className="font-mono text-xs text-coral mb-5">THE INTERNET IS FULL OF NICE-ENOUGH THINGS.</p><h1 className="text-[clamp(4.5rem,14vw,13rem)] font-semibold tracking-[-.09em] leading-[.78] max-w-6xl">I BUILD<br/><span className="text-acid">OTHER</span><br/>WORLDS.</h1><div className="flex justify-between items-end mt-12"><p className="max-w-xs text-lg leading-7 text-paper/70">Sandesh Dahal is an independent software engineer turning ambitious ideas into digital places with a pulse.</p><a href="#work" className="size-20 md:size-28 rounded-full bg-coral text-ink flex flex-col items-center justify-center font-mono text-xs hover:scale-110 transition-transform">SCROLL<br/><ArrowDownRight className="size-5 mt-1"/></a></div></div></section>
    <div className="border-y border-paper/15 overflow-hidden py-4 whitespace-nowrap font-mono text-xs text-muted"><div className="marquee inline-flex gap-10">PRODUCTS WITH A PULSE ✦ WEB EXPERIENCES THAT MOVE ✦ COMMISSIONS OPEN ✦ PRODUCTS WITH A PULSE ✦ WEB EXPERIENCES THAT MOVE ✦ COMMISSIONS OPEN ✦</div></div>
    <section id="work" className="px-5 md:px-10 py-28"><div className="flex justify-between items-end mb-12"><div><span className="font-mono text-xs text-acid">02 / SELECTED WORLDS</span><h2 className="text-5xl md:text-8xl tracking-[-.07em] leading-none mt-4">Proof of<br/>play.</h2></div><Sparkles className="text-coral size-10 hidden md:block"/></div><div className="grid md:grid-cols-3 gap-4">{projects.map((p,i)=><article key={p.name} className={`group min-h-[420px] p-6 flex flex-col justify-between ${p.color} ${i===2?'text-ink':'text-ink'} hover:-translate-y-3 transition-transform duration-500`}><div className="flex justify-between font-mono text-xs"><span>0{i+1}</span><span>{p.year}</span></div><div><div className="font-mono text-xs mb-4 opacity-70">{p.type}</div><h3 className="text-4xl font-semibold tracking-[-.06em]">{p.name}</h3><p className="mt-4 max-w-xs leading-6">{p.text}</p><div className="flex flex-wrap gap-2 mt-6">{p.tags.map(t=><span key={t} className="border border-current/30 px-2 py-1 font-mono text-[10px]">{t}</span>)}</div></div><ArrowUpRight className="self-end size-8 group-hover:rotate-45 transition-transform"/></article>)}</div></section>
    <section className="px-5 md:px-10 py-24 border-t border-paper/15 grid md:grid-cols-2 gap-16"><div><span className="font-mono text-xs text-coral">03 / HOW I PLAY</span><h2 className="text-5xl md:text-7xl tracking-[-.07em] leading-none mt-4">Not a pair<br/>of hands.<br/><span className="text-acid">A whole team.</span></h2></div><div className="flex flex-col gap-0">{['Shape the idea','Design the feeling','Build the machine','Ship the memorable'].map((x,i)=><button key={x} onClick={()=>setScore(score+i+1)} className="group flex items-center justify-between border-b border-paper/20 py-6 text-left hover:text-acid transition-colors"><span className="font-mono text-xs">0{i+1}</span><span className="text-2xl md:text-4xl tracking-[-.04em]">{x}</span><ArrowUpRight className="group-hover:rotate-45 transition-transform"/></button>)}<p className="font-mono text-xs text-muted mt-8">CLICK THE STEPS. YES, THAT&apos;S A TINY GAME. SCORE: {score}</p></div></section>
    <section id="contact" className="px-5 md:px-10 py-28 bg-acid text-ink"><div className="max-w-5xl"><span className="font-mono text-xs">04 / OPEN CHANNEL</span><h2 className="text-[clamp(4rem,11vw,10rem)] font-semibold tracking-[-.09em] leading-[.8] mt-6">Have a<br/><span className="text-coral">strange</span><br/>idea?</h2><form onSubmit={send} className="mt-16 grid md:grid-cols-2 gap-4 max-w-3xl"><input required name="name" placeholder="YOUR NAME" className="bg-transparent border-b border-ink/40 py-4 outline-none font-mono text-sm placeholder:text-ink/60"/><input required type="email" name="email" placeholder="YOUR EMAIL" className="bg-transparent border-b border-ink/40 py-4 outline-none font-mono text-sm placeholder:text-ink/60"/><textarea required name="message" placeholder="TELL ME THE GOOD PART" rows={3} className="bg-transparent border-b border-ink/40 py-4 outline-none font-mono text-sm placeholder:text-ink/60 md:col-span-2"/><button className="bg-ink text-paper px-6 py-4 font-mono text-xs justify-self-start hover:bg-coral transition-colors"><Mail className="inline size-4 mr-2"/> SEND A SIGNAL</button></form><p aria-live="polite" className="font-mono text-xs mt-5">{message}</p></div></section>
    <footer className="px-5 md:px-10 py-8 flex justify-between font-mono text-xs text-muted"><span>© 2026 SD STUDIO</span><span>BUILT WITH CURIOSITY <Gamepad2 className="inline size-4 ml-1 text-acid"/></span></footer>
  </main>
}
